<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>uap10.0.19041</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <OutputType>AppContainerExe</OutputType>
    <RootNamespace>HandwritingCalculatorUwp</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Include="App.xaml" />
    <Page Include="MainPage.xaml" />
    <AppxManifest Include="Package.appxmanifest" />
  </ItemGroup>
</Project>
